In [2]:
import numpy as np

n1 = np.array([1,2,3,4,5])
print(n1) # [1 2 3 4 5]

# 配列の次元数は np.ndim() 関数で取得可能
np.ndim(n1) # 1 -> 1次元

# 配列の形状取得にはshapeを使う。タプルでかえってくる
n1.shape # (5,) # 変数n1の形状を取得

"""
2次元配列 (5,3)

3次元配列 (5,5,4)

1次元でも2次元でも、同様にタプルで結果が返される。
"""

# 3行2列の配列（2次元の配列）を作成

"""
2次元配列は行列のことを意味します。
3 × 2 の配列は、最初の次元に3つ要素があり、
次の次元に2つの要素があるという意味。

行(row) 配列の横方向
列(column) 配列の縦方向
"""

n2 = np.array([[1,2], [3,4], [5,6]])
print(n2)

"""
[[1 2]
 [3 4]
 [5 6]]
"""
print(n2.ndim) # 2

[1 2 3 4 5]
[[1 2]
 [3 4]
 [5 6]]
2
