In [1]:
import numpy as  np
# データの準備
# 等間隔の数字
# 0から9までの数字(配列)を生成
x = np.arange(10)
print(x)

# reshape()は配列を形状に変換します
x = np.arange(1, 10).reshape(3,3) # 3×3の多次元配列に変換
y = np.arange(1, 10).reshape(3,3) # 3×3の多次元配列に変換
"""
xを下記のように書き換えることも可能
x = np.reshape(x, (3,3))
"""
print(x)
print(y)

print(x + y)
print(x - y)
print(x * y)

print("---------------------")


sample_array = np.arange(10)
print(sample_array)

# reshapeを使って配列の形状を指定
sample_array2 = sample_array.reshape(2,5)
print(sample_array2) #array(([0,1,2,3,4],[5,6,7,8,9]])

# concatenateを使って、データの結合する(axisで行方向か、縦方向を指定可能)
sample_array3 = np.array([[1,2,3],[4,5,6]])
sample_array4 = np.array([[7,8,9],[10,11,12]])

# 行方向に結合 ([[1,2,3,7,8,9],4,5,6,10,11,12]])
print(np.concatenate([sample_array3,sample_array4],axis=1))

# hstackでも行方向の結合が可能
print(np.hstack((sample_array3,sample_array4)))



"""
axis=0で列方向
axis=1で行方向です。
下記URLを参考ください。
https://qiita.com/shuetsu@github/items/2bf8bba233c5ecc7a0ad
"""

# axisに0を設定しているので、列方向 ([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(np.concatenate([sample_array3,sample_array4],axis=0))

# vstackで列方向の結合が可能
print(np.vstack((sample_array3,sample_array4)))

[0 1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
---------------------
[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
