In [1]:
import numpy as  np
# データの準備
# 等間隔の数字
# 0から9までの数字(配列)を生成
x = np.arange(10)
print(x)

# reshape()は配列を形状に変換します
x = np.arange(1, 10).reshape(3,3) # 3×3の多次元配列に変換
y = np.arange(1, 10).reshape(3,3) # 3×3の多次元配列に変換
"""
xを下記のように書き換えることも可能
x = np.reshape(x, (3,3))
"""
print(x)
print(y)

print(x + y)
print(x - y)
print(x * y)

[0 1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
